Product.create({:name=>"Jeans", :price => 11})
Product.create({:name=>"Shirt", :price => 30.50})
Product.create({:name=>"Tees", :price => 15.40})
Product.create({:name=>"Trouser", :price => 8})
Product.create({:name=>"Skirt", :price => 7.30})
